clean:
	cd calc; $(MAKE) clean
	cd cgi; $(MAKE) clean
	cd lexyacc; $(MAKE) clean
	cd manual; $(MAKE) clean
	cd mls; $(MAKE) clean
	cd parsercomb; $(MAKE) clean
	cd pretty; $(MAKE) clean
	cd webserver; $(MAKE) clean
